// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./components/Navbar.vue')['default']
    ParkingForm: typeof import('./components/ParkingForm.vue')['default']
    TableVehicles: typeof import('./components/TableVehicles.vue')['default']
  }
}

export { }
